name: ShortswithBalls
favicon: null
layout_spectrum: 0.35887494147755206
typography_spectrum: 0.48709601163864136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.35061907465569675
  lightness: 0.748701422708109
  saturation: 0.9364858304616064
  rhythmicContrast: 0.8981957796495408
purpose: []
